server:
  port: 8082
  servlet:
    context-path: /api/v1

  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: energybox_user
    url: jdbc:postgresql://localhost:5432/energybox_db
    password: energybox_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
